# Generated by Django 5.2.8 on 2025-11-27 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('SICK', 'Sick'), ('HOLIDAY', 'Holiday'), ('FIELD_TRIP', 'Field Trip')], default='PRESENT', max_length=20)),
                ('general_notes', models.TextField(blank=True, help_text='Optional notes for the day')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='academics.student')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Log',
                'verbose_name_plural': 'Daily Logs',
                'ordering': ['-date', 'student__name'],
            },
        ),
        migrations.CreateModel(
            name='CourseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(help_text='Notes about what was covered in this course today')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_notes', to='academics.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_notes', to=settings.AUTH_USER_MODEL)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_notes', to='academics.dailylog')),
            ],
            options={
                'verbose_name': 'Course Note',
                'verbose_name_plural': 'Course Notes',
                'ordering': ['course__name'],
            },
        ),
        migrations.AddIndex(
            model_name='dailylog',
            index=models.Index(fields=['date', 'student'], name='academics_d_date_796ba7_idx'),
        ),
        migrations.AddIndex(
            model_name='dailylog',
            index=models.Index(fields=['user', 'date'], name='academics_d_user_id_3a1a7a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailylog',
            unique_together={('student', 'date')},
        ),
        migrations.AddIndex(
            model_name='coursenote',
            index=models.Index(fields=['daily_log', 'course'], name='academics_c_daily_l_d4d28b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coursenote',
            unique_together={('daily_log', 'course')},
        ),
    ]
