# Generated by Django 5.2.8 on 2025-11-28 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_student_grade_level_resource'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Algebra 1', 'Latin'", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description of the course')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course Template',
                'verbose_name_plural': 'Course Templates',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='coursenote',
            options={'ordering': ['course_enrollment__course__name'], 'verbose_name': 'Course Note', 'verbose_name_plural': 'Course Notes'},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='coursenote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='course',
            name='resources',
            field=models.ManyToManyField(blank=True, help_text='Resources for this course', related_name='courses', to='academics.resource'),
        ),
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text="e.g., 'Algebra 1', 'Latin'", max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='school_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_courses', to='academics.schoolyear'),
        ),
        migrations.AlterField(
            model_name='course',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_courses', to='academics.student'),
        ),
        migrations.AlterField(
            model_name='coursenote',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_course_notes', to='academics.course'),
        ),
        migrations.AlterField(
            model_name='curriculumresource',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_curriculum_resources', to='academics.course'),
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('PAUSED', 'Paused')], default='IN_PROGRESS', max_length=20)),
                ('started_date', models.DateField(blank=True, help_text='Date the student started this course', null=True)),
                ('completed_date', models.DateField(blank=True, help_text='Date the student completed this course', null=True)),
                ('final_grade', models.CharField(blank=True, help_text="Final grade (e.g., 'A', '95%', 'Pass')", max_length=5)),
                ('completion_percentage', models.IntegerField(blank=True, help_text='Completion percentage (0-100)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.course')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='academics.schoolyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='academics.student')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Enrollment',
                'verbose_name_plural': 'Course Enrollments',
                'ordering': ['school_year__start_date', 'course__name'],
            },
        ),
        migrations.AddField(
            model_name='coursenote',
            name='course_enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_notes', to='academics.courseenrollment'),
        ),
        migrations.AddIndex(
            model_name='coursenote',
            index=models.Index(fields=['daily_log', 'course_enrollment'], name='academics_c_daily_l_f32572_idx'),
        ),
        migrations.AddField(
            model_name='coursetemplate',
            name='suggested_resources',
            field=models.ManyToManyField(blank=True, help_text='Suggested resources for this course template', related_name='course_templates', to='academics.resource'),
        ),
        migrations.AddField(
            model_name='coursetemplate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='course_template',
            field=models.ForeignKey(blank=True, help_text='Template this course was created from (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='academics.coursetemplate'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['user', 'name'], name='academics_c_user_id_887979_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['student', 'school_year'], name='academics_c_student_e23f23_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['course', 'school_year'], name='academics_c_course__b9ee7c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courseenrollment',
            unique_together={('student', 'course', 'school_year')},
        ),
        migrations.AddIndex(
            model_name='coursetemplate',
            index=models.Index(fields=['user', 'name'], name='academics_c_user_id_7faedd_idx'),
        ),
    ]
