# Generated by Django 5.2.8 on 2025-11-28 05:49

from django.db import migrations


def migrate_course_data(apps, schema_editor):
    """Migrate existing Course data to new CourseEnrollment architecture."""
    Course = apps.get_model('academics', 'Course')
    CourseEnrollment = apps.get_model('academics', 'CourseEnrollment')
    CourseNote = apps.get_model('academics', 'CourseNote')
    CurriculumResource = apps.get_model('academics', 'CurriculumResource')
    Resource = apps.get_model('academics', 'Resource')

    # Step 1: Set user on all Course records
    for course in Course.objects.all():
        if course.student:
            course.user = course.student.user
            course.save()

    # Step 2: Create CourseEnrollments for all existing Courses
    enrollment_map = {}  # Map (course_id, student_id, school_year_id) -> enrollment_id

    for course in Course.objects.all():
        if course.student and course.school_year:
            # Create enrollment
            enrollment = CourseEnrollment.objects.create(
                user=course.user,
                student=course.student,
                course=course,
                school_year=course.school_year,
                status='IN_PROGRESS',
            )
            # Track mapping
            key = (course.id, course.student.id, course.school_year.id)
            enrollment_map[key] = enrollment.id

    # Step 3: Update CourseNotes to reference CourseEnrollments
    for note in CourseNote.objects.all():
        if note.course and note.daily_log:
            # Find the enrollment for this course + student + school year
            # We need to get the school year from the student's enrollments
            course = note.course
            student = note.daily_log.student

            # Find which school year this daily log falls into
            from datetime import date
            log_date = note.daily_log.date

            # Try to find a school year that contains this date
            if course.school_year:
                school_year = course.school_year
                key = (course.id, student.id, school_year.id)

                if key in enrollment_map:
                    note.course_enrollment_id = enrollment_map[key]
                    note.save()

    # Step 4: Migrate CurriculumResource to Resource library
    # Deduplicate by ISBN (if available) or by title+author
    resource_map = {}  # Map old CurriculumResource ID -> new Resource ID

    for curr_res in CurriculumResource.objects.all():
        # Try to find existing resource
        resource = None

        if curr_res.course and curr_res.course.user:
            user = curr_res.course.user

            # Try to find by ISBN first
            if curr_res.isbn:
                resource = Resource.objects.filter(
                    user=user,
                    isbn=curr_res.isbn
                ).first()

            # If not found by ISBN, try by title+author
            if not resource and curr_res.title:
                resource = Resource.objects.filter(
                    user=user,
                    title=curr_res.title,
                    author=curr_res.author or ''
                ).first()

            # If still not found, create new resource
            if not resource:
                resource = Resource.objects.create(
                    user=user,
                    title=curr_res.title,
                    author=curr_res.author or '',
                    publisher=curr_res.publisher or '',
                    isbn=curr_res.isbn or '',
                    resource_type='BOOK',  # Default to book
                    description=curr_res.notes or '',
                )

            # Track mapping
            resource_map[curr_res.id] = resource.id

            # Link resource to course
            if curr_res.course:
                curr_res.course.resources.add(resource)


def reverse_migrate_course_data(apps, schema_editor):
    """Reverse migration - not fully implemented as this is a one-way migration."""
    # This would be complex to reverse, and since we're working with test data,
    # we can just accept that this migration is one-way
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_coursetemplate_alter_course_options_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_course_data, reverse_migrate_course_data),
    ]
