# Generated by Django 5.2.8 on 2025-11-28 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_tag_resource_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Grade name (e.g., '1st Grade', 'Year 1', 'Upper Elementary')", max_length=100)),
                ('order', models.IntegerField(help_text='Numeric order for sorting (e.g., 0 for PK, 1 for K, 2 for 1st)')),
                ('description', models.TextField(blank=True, help_text='Optional description of this grade level')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_levels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grade Level',
                'verbose_name_plural': 'Grade Levels',
                'ordering': ['order'],
                'unique_together': {('user', 'name'), ('user', 'order')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='grade_level',
            field=models.ForeignKey(blank=True, help_text='Optional grade level this course is designed for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='academics.gradelevel'),
        ),
        migrations.CreateModel(
            name='StudentGradeYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_years', to='academics.gradelevel')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_grades', to='academics.schoolyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_years', to='academics.student')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_grade_years', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Grade Assignment',
                'verbose_name_plural': 'Student Grade Assignments',
                'ordering': ['school_year__start_date', 'student__name'],
                'indexes': [models.Index(fields=['student', 'school_year'], name='academics_s_student_e2c4df_idx'), models.Index(fields=['school_year', 'grade_level'], name='academics_s_school__e2d3b8_idx')],
                'unique_together': {('student', 'school_year')},
            },
        ),
    ]
