# Generated by Django 5.2.8 on 2025-11-29 04:18

import idahomeschool.academics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_gradelevel_course_grade_level_studentgradeyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, help_text='Student photo (optional)', null=True, upload_to=idahomeschool.academics.models.student_photo_path),
        ),
    ]
