# Generated by Django 5.2.8 on 2025-11-29 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_default_color_palettes(apps, schema_editor):
    """Create default color palette for all existing users."""
    User = apps.get_model(settings.AUTH_USER_MODEL)
    ColorPalette = apps.get_model('academics', 'ColorPalette')

    # Default color palette
    default_colors = [
        ("#007bff", "Blue"),
        ("#28a745", "Green"),
        ("#dc3545", "Red"),
        ("#ffc107", "Yellow"),
        ("#17a2b8", "Cyan"),
        ("#6f42c1", "Purple"),
        ("#fd7e14", "Orange"),
        ("#e83e8c", "Pink"),
        ("#20c997", "Teal"),
        ("#6c757d", "Gray"),
        ("#343a40", "Dark"),
        ("#f8f9fa", "Light Gray"),
    ]

    # Create color palette entries for each user
    for user in User.objects.all():
        for color, name in default_colors:
            ColorPalette.objects.create(
                user=user,
                color=color,
                name=name,
            )


def reverse_seed_default_color_palettes(apps, schema_editor):
    """Remove seeded color palettes (reverse migration)."""
    ColorPalette = apps.get_model('academics', 'ColorPalette')
    # Delete all color palette entries
    ColorPalette.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_add_student_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorPalette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text="Optional name for the color (e.g., 'Ocean Blue')", max_length=50)),
                ('color', models.CharField(help_text='Hex color code (e.g., #007bff)', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_palette', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Color Palette',
                'verbose_name_plural': 'Color Palettes',
                'ordering': ['created_at'],
            },
        ),
        migrations.RunPython(
            seed_default_color_palettes,
            reverse_seed_default_color_palettes,
        ),
    ]
