# Generated by Django 5.2.8 on 2025-11-29 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_default_groups_and_assign_colors(apps, schema_editor):
    """Create a 'Default' group for each user and assign all their existing colors to it."""
    User = apps.get_model(settings.AUTH_USER_MODEL)
    ColorPaletteGroup = apps.get_model('academics', 'ColorPaletteGroup')
    ColorPalette = apps.get_model('academics', 'ColorPalette')

    for user in User.objects.all():
        # Create default group for this user
        default_group = ColorPaletteGroup.objects.create(
            user=user,
            name='Default',
            is_active=True,
        )

        # Assign all existing colors for this user to the default group
        user_colors = ColorPalette.objects.filter(user=user)
        for color in user_colors:
            color.groups.add(default_group)


def reverse_create_default_groups(apps, schema_editor):
    """Remove all ColorPaletteGroup instances."""
    ColorPaletteGroup = apps.get_model('academics', 'ColorPaletteGroup')
    ColorPaletteGroup.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_add_color_palette'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorPaletteGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False, help_text='Only colors from the active group are used for random tag colors')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_palette_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Color Palette Group',
                'verbose_name_plural': 'Color Palette Groups',
                'ordering': ['-is_active', 'name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.AddField(
            model_name='colorpalette',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Groups this color belongs to', related_name='colors', to='academics.colorpalettegroup'),
        ),
        migrations.RunPython(
            create_default_groups_and_assign_colors,
            reverse_create_default_groups,
        ),
    ]
