# Generated by Django 5.2.8 on 2025-11-29 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_rename_color_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['created_at'], 'verbose_name': 'Color', 'verbose_name_plural': 'Colors'},
        ),
        migrations.AlterModelOptions(
            name='colorpalette',
            options={'ordering': ['-is_active', 'name'], 'verbose_name': 'Color Palette', 'verbose_name_plural': 'Color Palettes'},
        ),
        migrations.AlterField(
            model_name='color',
            name='palettes',
            field=models.ManyToManyField(blank=True, help_text='Palettes this color belongs to', related_name='colors', to='academics.colorpalette'),
        ),
        migrations.AlterField(
            model_name='colorpalette',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Only colors from the active palette are used for random tag colors'),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='status',
            field=models.CharField(blank=True, choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('SICK', 'Sick'), ('HOLIDAY', 'Holiday'), ('FIELD_TRIP', 'Field Trip')], default='PRESENT', max_length=20),
        ),
        migrations.CreateModel(
            name='AttendanceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Internal code for this status (e.g., 'PRESENT', 'SICK')", max_length=50)),
                ('label', models.CharField(help_text="Display name for this status (e.g., 'Present', 'Sick')", max_length=50)),
                ('abbreviation', models.CharField(help_text="Short code shown on calendar (e.g., 'P', 'A', 'S')", max_length=3)),
                ('color', models.CharField(help_text='Hex color code for the status badge (e.g., #007bff)', max_length=7)),
                ('is_instructional', models.BooleanField(default=True, help_text='Whether this status counts as an instructional day')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default status for new daily logs')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which statuses are displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance Status',
                'verbose_name_plural': 'Attendance Statuses',
                'ordering': ['user', 'display_order', 'label'],
            },
        ),
        migrations.AddField(
            model_name='dailylog',
            name='attendance_status',
            field=models.ForeignKey(blank=True, help_text='Attendance status for this day', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_logs', to='academics.attendancestatus'),
        ),
        migrations.AddIndex(
            model_name='attendancestatus',
            index=models.Index(fields=['user', 'is_default'], name='academics_a_user_id_10f035_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancestatus',
            index=models.Index(fields=['user', 'display_order'], name='academics_a_user_id_32ef45_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancestatus',
            unique_together={('user', 'code')},
        ),
    ]
