# Generated by Django 5.2.8 on 2025-11-29 23:14

from django.db import migrations


def create_default_statuses_and_migrate_logs(apps, schema_editor):
    """Create default attendance statuses for all users and migrate existing logs."""
    User = apps.get_model("users", "User")
    AttendanceStatus = apps.get_model("academics", "AttendanceStatus")
    DailyLog = apps.get_model("academics", "DailyLog")
    ColorPalette = apps.get_model("academics", "ColorPalette")

    # Default statuses configuration
    default_statuses = [
        {
            "code": "PRESENT",
            "label": "Present",
            "abbreviation": "P",
            "color": "#198754",
            "is_instructional": True,
            "is_default": True,
        },
        {
            "code": "ABSENT",
            "label": "Absent",
            "abbreviation": "A",
            "color": "#dc3545",
            "is_instructional": False,
            "is_default": False,
        },
        {
            "code": "SICK",
            "label": "Sick",
            "abbreviation": "S",
            "color": "#ffc107",
            "is_instructional": False,
            "is_default": False,
        },
        {
            "code": "HOLIDAY",
            "label": "Holiday",
            "abbreviation": "H",
            "color": "#0dcaf0",
            "is_instructional": False,
            "is_default": False,
        },
        {
            "code": "FIELD_TRIP",
            "label": "Field Trip",
            "abbreviation": "F",
            "color": "#0d6efd",
            "is_instructional": True,
            "is_default": False,
        },
    ]

    # Create default statuses for each user
    for user in User.objects.all():
        # Try to get active palette colors
        active_palette = ColorPalette.objects.filter(
            user=user,
            is_active=True,
        ).first()

        user_status_map = {}

        for idx, status_data in enumerate(default_statuses):
            color_value = status_data["color"]

            # Try to use color from active palette if available
            if active_palette:
                palette_color = active_palette.colors.filter(
                    color=color_value,
                ).first()
                if palette_color:
                    color_value = palette_color.color

            status = AttendanceStatus.objects.create(
                user=user,
                code=status_data["code"],
                label=status_data["label"],
                abbreviation=status_data["abbreviation"],
                color=color_value,
                is_instructional=status_data["is_instructional"],
                is_default=status_data["is_default"],
                display_order=idx,
            )
            user_status_map[(user.id, status_data["code"])] = status

        # Migrate existing DailyLog records for this user
        for log in DailyLog.objects.filter(user=user):
            status_code = log.status or "PRESENT"
            status_obj = user_status_map.get((user.id, status_code))
            if status_obj:
                log.attendance_status = status_obj
                log.save(update_fields=["attendance_status"])


def reverse_migration(apps, schema_editor):
    """Reverse the migration by removing all AttendanceStatus records."""
    AttendanceStatus = apps.get_model("academics", "AttendanceStatus")
    AttendanceStatus.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_add_custom_attendance_statuses'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_default_statuses_and_migrate_logs,
            reverse_migration,
        ),
    ]
