# Generated by Django 5.2.8 on 2025-11-30 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_migrate_attendance_status_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTagPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags that identify resources as books for the reading list', related_name='book_preferences', to='academics.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_tag_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Book Tag Preference',
                'verbose_name_plural': 'Book Tag Preferences',
            },
        ),
        migrations.CreateModel(
            name='ReadingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('TO_READ', 'To Read'), ('READING', 'Currently Reading'), ('COMPLETED', 'Completed'), ('DID_NOT_FINISH', 'Did Not Finish')], default='TO_READ', max_length=20)),
                ('started_date', models.DateField(blank=True, help_text='Date the student started reading this book', null=True)),
                ('completed_date', models.DateField(blank=True, help_text='Date the student completed or stopped reading this book', null=True)),
                ('rating', models.IntegerField(blank=True, help_text='Rating from 1-5 stars', null=True)),
                ('notes', models.TextField(blank=True, help_text='Personal notes, review, or thoughts about the book')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_list_entries', to='academics.resource')),
                ('school_year', models.ForeignKey(blank=True, help_text='Optional school year when this book was read', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reading_list_entries', to='academics.schoolyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_list', to='academics.student')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reading List Entry',
                'verbose_name_plural': 'Reading List Entries',
                'ordering': ['-updated_at', 'student__name'],
                'indexes': [models.Index(fields=['student', 'status'], name='academics_r_student_f2d72a_idx'), models.Index(fields=['user', 'status'], name='academics_r_user_id_b4fb15_idx'), models.Index(fields=['student', 'school_year'], name='academics_r_student_2094b7_idx')],
                'unique_together': {('student', 'resource')},
            },
        ),
    ]
