# Generated by Django 5.2.8 on 2025-11-30 01:23

import idahomeschool.academics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_booktagpreference_readinglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional cover image or thumbnail', null=True, upload_to=idahomeschool.academics.models.resource_image_path),
        ),
    ]
